"use client";
import { useState } from "react";
import { projectTypes, type ProjectType, type EconomyMode } from "@/lib/eidolon";
export default function Launch() {
 const [step,setStep]=useState(0); const [type,setType]=useState<ProjectType|null>(null); const [economy,setEconomy]=useState<EconomyMode>("none"); const [published,setPublished]=useState(false);
 if(published) return <main className="surface"><div className="panel success"><span className="eyebrow">PROJECT CREATED</span><h1>Your project has a place in EIDOLON.</h1><p>Discovery is ready. The economy layer remains optional and can be activated later.</p><a href="/discover">Enter discovery →</a></div></main>;
 return <main className="surface"><header className="surface-nav"><a href="/" className="wordmark">EIDOLON</a><span>LAUNCH / {String(step+1).padStart(2,"0")} — 03</span></header><section className="launch-panel">
 {step===0&&<><div className="eyebrow">01 / THE OBJECT</div><h1>What are you bringing<br/><em>into the world?</em></h1><div className="type-grid">{projectTypes.map(x=><button className={type===x?"choice active":"choice"} onClick={()=>setType(x)} key={x}>{x}<span>↗</span></button>)}</div><button className="primary" disabled={!type} onClick={()=>setStep(1)}>Continue</button></>}
 {step===1&&<><div className="eyebrow">02 / IDENTITY</div><h1>Give it a<br/><em>presence.</em></h1><div className="form"><label>Project name<input placeholder="e.g. NOVA"/></label><label>Source / website<input placeholder="https://"/></label><label>One sentence<textarea placeholder="What is this project?" rows={3}/></label></div><button className="primary" onClick={()=>setStep(2)}>Continue</button></>}
 {step===2&&<><div className="eyebrow">03 / ECONOMY</div><h1>With an economy<br/><em>or without one?</em></h1><div className="economy-grid"><button className={economy==="none"?"economy active":"economy"} onClick={()=>setEconomy("none")}><strong>No token</strong><span>Launch the project on its own.</span></button><button className={economy==="token"?"economy active":"economy"} onClick={()=>setEconomy("token")}><strong>With a token</strong><span>Prepare a native project economy.</span></button></div>{economy==="token"&&<div className="token-note">Real wallet/chain infrastructure will power deployment — never simulated.</div>}<button className="primary" onClick={()=>setPublished(true)}>Publish project</button></>}
 </section></main>;
}
