"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { projectActionDescriptions, projectActionLabels, type Project, type ProjectAction } from "@/lib/eidolon";

export default function ProjectPage(){
 const [project,setProject]=useState<Project|null>(null),[economy,setEconomy]=useState<any>(null),[isFollowing,setIsFollowing]=useState(false),[authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(true),[followBusy,setFollowBusy]=useState(false),[error,setError]=useState<string|null>(null),[followError,setFollowError]=useState<string|null>(null),[githubMessage,setGithubMessage]=useState<string|null>(null);
 const load=()=>{const slug=new URLSearchParams(window.location.search).get("slug");if(!slug){setError("Missing project slug.");setLoading(false);return;}fetch("/api/project?slug="+encodeURIComponent(slug),{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Project could not be loaded.");return d}).then(d=>{setProject(d.project);setEconomy(d.economyDetail);setIsFollowing(Boolean(d.isFollowing));setAuthenticated(Boolean(d.authenticated))}).catch(e=>setError(e instanceof Error?e.message:"Project could not be loaded.")).finally(()=>setLoading(false))};
 useEffect(()=>{const result=new URLSearchParams(window.location.search).get("github");if(result==="verified")setGithubMessage("GitHub control verified. This source is now backed by the connected account.");else if(result)setGithubMessage("GitHub connection completed, but this repository is still awaiting proof.");load()},[]);
 const toggleFollow=async()=>{if(!project||followBusy)return;if(!authenticated){window.location.href="/auth?next="+encodeURIComponent(window.location.pathname+window.location.search);return;}setFollowBusy(true);setFollowError(null);try{const response=await fetch("/api/project/follow"+(isFollowing?"?projectId="+encodeURIComponent(project.id):""),{method:isFollowing?"DELETE":"POST",headers:isFollowing?undefined:{"content-type":"application/json"},body:isFollowing?undefined:JSON.stringify({projectId:project.id})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Follow could not be updated.");setIsFollowing(Boolean(data.following));}catch(e){setFollowError(e instanceof Error?e.message:"Follow could not be updated.");}finally{setFollowBusy(false)}};
 const verifySource=async()=>{if(!project||!authenticated)return;setFollowError(null);const response=await fetch("/api/project/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:project.id})});const data=await response.json();if(response.ok&&data.status==="verified"){setProject({...project,source:{...project.source,status:"verified",verifiedAt:new Date().toISOString()}});setGithubMessage(data.message)}else setFollowError(data.message??data.error??"Verification could not be completed.");};
 if(loading)return <main className="project-page"><header className="surface-nav"><Link href="/" className="wordmark">EIDOLON</Link><span>PROJECT</span></header><section className="project-hero"><div className="eyebrow">LOADING PROJECT</div><h1>Reading the network.</h1></section></main>;
 if(error||!project)return <main className="project-page"><header className="surface-nav"><Link href="/" className="wordmark">EIDOLON</Link><span>PROJECT</span></header><section className="project-hero"><div className="eyebrow">PROJECT UNAVAILABLE</div><h1>{error??"Project not found."}</h1><p><Link href="/discover">Return to discovery →</Link></p></section></main>;
 const actions=project.actions.length?project.actions:["use","follow"] as ProjectAction[]; const useAction=actions.includes("use");
 return <main className="project-page"><header className="surface-nav"><Link href="/" className="wordmark">EIDOLON</Link><span>PROJECT / {project.name}</span></header><section className="project-hero"><div className="eyebrow">{project.type} · {project.source.kind.toUpperCase()} · {project.source.status.toUpperCase()}</div><h1>{project.name}</h1><p>{project.description}</p><div className="project-actions">{useAction&&project.source.reference&&<a href={project.source.reference} target="_blank" rel="noreferrer" className="project-action-link">{projectActionLabels.use}</a>}<button onClick={toggleFollow} disabled={followBusy}>{followBusy?"Updating…":isFollowing?"Following":"Follow"}</button>{authenticated&&project.source.status==="pending"&&project.source.kind==="github"&&<><a className="project-action-link" href={"/api/github/connect?projectId="+encodeURIComponent(project.id)+"&next="+encodeURIComponent(window.location.pathname+window.location.search)}>Connect GitHub</a><button onClick={verifySource}>Verify GitHub</button></>}</div>{githubMessage&&<p className="action-note">{githubMessage}</p>}{followError&&<p className="action-error">{followError}</p>}{!authenticated&&<p className="action-note">Sign in to follow projects. Your follow is tied to your account.</p>}</section><section className="project-sections"><article><span className="eyebrow">IDENTITY</span><h2>Source identity</h2><p>The source is recorded, but EIDOLON never treats a declaration as proof of ownership.</p><div className="source-row"><strong>{project.source.kind.toUpperCase()}</strong><span>{project.source.status.toUpperCase()}</span></div>{project.source.reference&&<p>{project.source.reference}</p>}</article><article><span className="eyebrow">AVAILABLE ACTIONS</span><h2>What you can do</h2><div className="action-list">{actions.map(a=><div className="action-item" key={a}><strong>{projectActionLabels[a]}</strong><span>{projectActionDescriptions[a]}</span></div>)}</div></article><article><span className="eyebrow">ECONOMY</span><h2>{project.economy==="token"?"Token economy enabled":"No token enabled"}</h2><p>{project.economy==="token"?(economy?.chain?"Economy is configured for "+economy.chain+".":"Token configuration is persisted; chain details are not yet available."):"This project launched without a token. An economy can be activated later without changing the canonical project identity."}</p><Link className="economy-link" href="/economy">Explore economy →</Link></article><article><span className="eyebrow">GRAPH</span><h2>Connected projects</h2><p>Dependencies, collaborators, services and compositions will appear here as the network grows.</p></article></section></main>;
}
